# Generated by Django 5.1.4 on 2024-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_outcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_hours', models.PositiveIntegerField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'course_outcomes',
            },
        ),
    ]
